package com.sun.corba.se.PortableActivationIDL;


/**
* com/sun/corba/se/PortableActivationIDL/IIOP_CLEAR_TEXT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/adoptopenjdk/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-hotspot/workspace/build/src/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Tuesday, July 28, 2020 3:17:34 PM UTC
*/

public interface IIOP_CLEAR_TEXT
{

  /** Possible values for endpointType argument on Server.getEndpoint()
      * If you change the value of this constant then update
      * core.EndPoint accordingly.  It has a duplicate definition
      * to avoid a compilation dependency.
      */
  public static final String value = "IIOP_CLEAR_TEXT";
}
